### ISSUE TITLE
Compile Issue: TPaces.h

### ISSUE THREAD

**Issue by cnatzke** [GRIFFINCollaboration/GRSIData#79]
OS : Ubuntu 20.04.03
ROOT : v6.26/04
GRSISort : v4.0.0.3

The changes made in merge #78 cause compilation issues with TPaces. 

```
Compiling GRSIDataVersion.h                                           [OK]
Compiling .build/libraries/TGRSIAnalysis/TPaces/TPacesHit.o[ERROR]
In file included from libraries/TGRSIAnalysis/TPaces/TPacesHit.cxx:1:
/software/GRSISort/GRSIData/include/TPaces.h:33:23: error: 'Polar3DVector' in namespace 'ROOT::Math' does not name a type
   33 |    static ROOT::Math::Polar3DVector GetPosition(int DetNbr) { return gDetectorPosition[DetNbr]; } //!<!
      |                       ^~~~~~~~~~~~~
/software/GRSISort/GRSIData/include/TPaces.h:39:23: error: 'Polar3DVector' in namespace 'ROOT::Math' does not name a type
   39 |    static ROOT::Math::Polar3DVector gDetectorPosition[6]; //!<!  Position of each detector (plus one default position)
      |                       ^~~~~~~~~~~~~
libraries/TGRSIAnalysis/TPaces/TPacesHit.cxx: In member function 'virtual TVector3 TPacesHit::GetPosition(Double_t) const':
libraries/TGRSIAnalysis/TPaces/TPacesHit.cxx:63:19: error: 'GetPosition' is not a member of 'TPaces'
   63 |    return TPaces::GetPosition(GetDetector());
      |                   ^~~~~~~~~~~
make: *** [makefile:174: .build/libraries/TGRSIAnalysis/TPaces/TPacesHit.o] Error 1
```

**Comment by VinzenzBildstein** [comment]
Yes, just noticed this myself. This seems to be an issue with ROOT versions, apparently the new vectors only got introduced very recently (aka 6.26). I think the best way might be to remove those changes again or simply use the normal TVector3 with the cartesian coordinates calculated from the polar ones.

**Comment by cnatzke** [comment]
I checked the namespace [documentation](https://root.cern.ch/doc/master/namespaceROOT_1_1Math.html)
for v6.26 and I don't see any PolarVector classes. 

> simply use the normal TVector3 with the cartesian coordinates calculated from the polar ones.

I've done this before and it seems to work fine.

**Comment by VinzenzBildstein** [comment]
https://root.cern.ch/doc/master/namespaceROOT_1_1Math.html#aa455061348e886c280b314f0ce71acc8

**Comment by VinzenzBildstein** [comment]
I think my decision not to use TVector3 was based on this:

Attention
[TVector3](https://root.cern.ch/doc/master/classTVector3.html) is a legacy class. It is slower and worse for serialization than the recommended superior alternative [ROOT::Math::XYZVector](https://root.cern.ch/doc/master/namespaceROOT_1_1Math.html#a91b80e54b44a65c90d60e5c8ff128746).

More details can be found in the documentation of the [Physics Vectors](https://root.cern.ch/doc/master/group__GenVector.html) package.

**Comment by VinzenzBildstein** [comment]
It seems this class was almost always there though, I just checked and the Vector3Dfwd.h file is there for all root versions installed on our servers, starting from ROOT 5.34.38. So there are some other bugs in this. I will fix this and post the update asap

**Comment by VinzenzBildstein** [comment]
Okay, didn't know that GitHub automatically closes issues if they are mentioned as fixed in the PR. But I hope this compiles for you now in the latest version?

**Comment by cnatzke** [comment]
Everything compiles correctly now. Thanks for the fast fix on this!
